# Generated by Django 2.2.1 on 2019-05-04 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bankbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='ifsc',
            field=models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
